Azure-Samples/active-directory-xamarin-native-v2

README.md

A few suggestions and edits for the ReadMe...leave comments if you want me to change something back. 🐱

suggestions and edits for ReadMe

---

README.md

Complete the documentation in order to avoid false positive such as issue #23

Updating README.md with iOS considerations for Keychain

---

UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
UserDetailsClient/UserDetailsClient.Droid/packages.config
UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
UserDetailsClient/UserDetailsClient.iOS/AppDelegate.cs
UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
UserDetailsClient/UserDetailsClient.iOS/packages.config
UserDetailsClient/UserDetailsClient/App.cs
UserDetailsClient/UserDetailsClient/MainPage.xaml.cs
UserDetailsClient/UserDetailsClient/UserDetailsClient.csproj

update sample to msalv2.0.1-preview
Tested w/Android (system and embedded webview) and UWP (iOS simulator is not working...will try with a device soon)
Removed the `OnAppearing()` method because it was making an extra silent call every time the app appeared.

update to msal v2.0.1-preview

---

UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
UserDetailsClient/UserDetailsClient.Droid/packages.config
UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
UserDetailsClient/UserDetailsClient.iOS/packages.config
UserDetailsClient/UserDetailsClient/UserDetailsClient.csproj

tested w/UWP, android and iOS (yes, it's working again 🥇 )

update to msal2.3

---

UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
UserDetailsClient/UserDetailsClient.Droid/packages.config
UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
UserDetailsClient/UserDetailsClient.iOS/packages.config
UserDetailsClient/UserDetailsClient/UserDetailsClient.csproj

update to msal 2.4

---

UserDetailsClient/UserDetailsClient.Droid/packages.config
UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj

FIxing the package.json on the Android project.
Updating the UWP project to a recent version of Windows 10

FIxing the package.json on the Android project.

---

UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
UserDetailsClient/UserDetailsClient.Droid/packages.config
UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
UserDetailsClient/UserDetailsClient.iOS/packages.config
UserDetailsClient/UserDetailsClient/App.cs
UserDetailsClient/UserDetailsClient/MainPage.xaml.cs
UserDetailsClient/UserDetailsClient/UserDetailsClient.csproj

we had a customer run into issues because the error messages were not getting surfaced in this sample, so i made a few changes in addition to updating msal.

More logging and update to msal 4.3.1

---

UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
UserDetailsClient/UserDetailsClient.Droid/packages.config
UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
UserDetailsClient/UserDetailsClient.iOS/packages.config
UserDetailsClient/UserDetailsClient/UserDetailsClient.csproj

I think @bgavrilMS has a branch that includes overall fixes to the sample, but this one just updates the MSAL version.

update to msal 4.5

---

2-With-broker/README.md

- Highlighting that the fact that this step is for iOS only, not yet Android
- Step 4 is already done (Thanks Tiago for the feedback that this was confusing). Changing it to be "explanations"

Reacting to Tiago's feedback

---

1-Basic/README.md

Added a link to the latest Identity developer's introduction to MS Graph recording

Added a link to the latest Identity developer's introduction to MS Graph recording

---

README.md

Updating pre-requisites to install to be able to build the sample
Fixes https://github.com/Azure-Samples/active-directory-xamarin-native-v2/issues/104

Updating the pre-requisites in the README.md file

---

UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
UserDetailsClient/UserDetailsClient.Droid/packages.config
UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
UserDetailsClient/UserDetailsClient.iOS/packages.config
UserDetailsClient/UserDetailsClient/UserDetailsClient.csproj

Update MSAL to 4.8.0

---

1-Basic/UserDetailsClient/UserDetailsClient.Droid/MsalActivity.cs

Syncing dataScheme appId with defined appId on App.cs
Fix https://github.com/Azure-Samples/active-directory-xamarin-native-v2/issues/108

Fix for issue 108

---

1-Basic/README.md
2-With-broker/README.md
README.md

Added resource to setup Xamarin iOS on VS

Readme update

---

2-With-broker/README.md
2-With-broker/UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
2-With-broker/UserDetailsClient/UserDetailsClient.Droid/packages.config
2-With-broker/UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
2-With-broker/UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
2-With-broker/UserDetailsClient/UserDetailsClient/App.cs
2-With-broker/UserDetailsClient/UserDetailsClient/MainPage.xaml.cs
2-With-broker/UserDetailsClient/UserDetailsClient/UserDetailsClient.csproj

Enabling broker support for android.
We should probably re-test all of the flows here with the newest 4.9.0 package before we merge

Updating to 4.9.0

---

README.md

Revise Git Repository URL

---

2-With-broker/README.md

Improving steps for broker configuration.

Improving steps for broker configuration

---

1-Basic/UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
1-Basic/UserDetailsClient/UserDetailsClient.Droid/packages.config
1-Basic/UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
1-Basic/UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
2-With-broker/UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
2-With-broker/UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
2-With-broker/UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
2-With-broker/UserDetailsClient/UserDetailsClient.iOS/packages.config

Update MSAL version

---

2-With-broker/README.md

https://github.com/Azure-Samples/active-directory-xamarin-native-v2/issues/139

Addressing issue #139

---

2-With-broker/README.md

Adding more info on intent filters and the redirect URI

Broker documentation updates for android

---

1-Basic/UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
1-Basic/UserDetailsClient/UserDetailsClient.UWP/MainPage.xaml.cs
1-Basic/UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
1-Basic/UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
1-Basic/UserDetailsClient/UserDetailsClient/UserDetailsClient.csproj
2-With-broker/UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
2-With-broker/UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
2-With-broker/UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
2-With-broker/UserDetailsClient/UserDetailsClient/MainPage.xaml.cs
2-With-broker/UserDetailsClient/UserDetailsClient/UserDetailsClient.csproj

Tested with
1. Basic
2. With broker
for both Android (with device) and UWP.

Updating to MSAL 4.23.0

---

1-Basic/UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
1-Basic/UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
1-Basic/UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
1-Basic/UserDetailsClient/UserDetailsClient/UserDetailsClient.csproj
2-With-broker/UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
2-With-broker/UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
2-With-broker/UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
2-With-broker/UserDetailsClient/UserDetailsClient/App.cs
2-With-broker/UserDetailsClient/UserDetailsClient/UserDetailsClient.csproj

- needs to be updated w/release package (revmove -preview)

Content provider

---

1-Basic/UserDetailsClient/UserDetailsClient.Droid/Properties/AndroidManifest.xml
1-Basic/UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
2-With-broker/UserDetailsClient/UserDetailsClient.Droid/Properties/AndroidManifest.xml
2-With-broker/UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj

Tested and works out of the box

Adding support for android 11

---

1-Basic/UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
1-Basic/UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
1-Basic/UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
1-Basic/UserDetailsClient/UserDetailsClient/UserDetailsClient.csproj
2-With-broker/UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
2-With-broker/UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
2-With-broker/UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
2-With-broker/UserDetailsClient/UserDetailsClient/UserDetailsClient.csproj

Update to MSAL 4.29.0

---

1-Basic/UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
1-Basic/UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
1-Basic/UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
1-Basic/UserDetailsClient/UserDetailsClient/UserDetailsClient.csproj
2-With-broker/UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
2-With-broker/UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
2-With-broker/UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
2-With-broker/UserDetailsClient/UserDetailsClient/UserDetailsClient.csproj

Update to 4 30

---

1-Basic/UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
1-Basic/UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
1-Basic/UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
1-Basic/UserDetailsClient/UserDetailsClient/UserDetailsClient.csproj

Upgrade to 4.36

---

1-Basic/UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
1-Basic/UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
1-Basic/UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
1-Basic/UserDetailsClient/UserDetailsClient/UserDetailsClient.csproj
2-With-broker/UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
2-With-broker/UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
2-With-broker/UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
2-With-broker/UserDetailsClient/UserDetailsClient/UserDetailsClient.csproj
2-With-broker/active-directory-Xamarin-native-v2.sln

Update to MSAL 4.40.0

---

1-Basic/UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
1-Basic/UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
1-Basic/UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
1-Basic/UserDetailsClient/UserDetailsClient/UserDetailsClient.csproj
2-With-broker/UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
2-With-broker/UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
2-With-broker/UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
2-With-broker/UserDetailsClient/UserDetailsClient/UserDetailsClient.csproj

Upgrade to 4.43

---

1-Basic/UserDetailsClient/UserDetailsClient.Droid/MsalActivity.cs
1-Basic/UserDetailsClient/UserDetailsClient.Droid/Properties/AndroidManifest.xml
2-With-broker/UserDetailsClient/UserDetailsClient.Droid/MsalActivity.cs

Made samples compatible with Android API 32

Android compatibility with API 32
